### ISSUE TITLE
The `(boolean)` node cannot be captured

### ISSUE THREAD

**Issue by ObserverOfTime** [rest-nvim/tree-sitter-http#16]
It should either be added to the `(document)` choices, or be wrapped with `token()` (which may or may not work).

**Comment by NTBBloodbath** [comment]
Hi, sorry for the delay in replying!

That node is not currently in use, so it is not included in the document root node and therefore cannot be captured. This one is there because previously the parser had its own built-in JSON parser instead of embedding the already existing parser and I forgot to do a cleanup, this node will no longer exist in the next version of the parser that is in the 'next' branch.
